#!/bin/bash

FIFO_TO_SERVER_NAME=/tmp/led_from_client_fifo
FIFO_TO_CLIENT_NAME=/tmp/led_to_client_fifo


#cat ${FIFO_TO_CLIENT_NAME} &

while read line; do
  echo "${line}" > ${FIFO_TO_SERVER_NAME}
done < /dev/stdin
